# Generated by Django 5.1.4 on 2024-12-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True)),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('home_team_score', models.IntegerField()),
                ('away_team_score', models.IntegerField()),
                ('result_home_team_score', models.IntegerField(null=True)),
                ('result_away_team_score', models.IntegerField(null=True)),
                ('league', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=100)),
            ],
        ),
    ]
