# Generated by Django 5.1.4 on 2024-12-29 11:31

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fixture_created_at_alter_fixture_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
