# Generated by Django 5.1.4 on 2025-01-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_fixture_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='league',
            field=models.CharField(choices=[('premier league', 'pl'), ('championship', 'ch'), ('league 1', 'lg1'), ('epl league 1', 'epl1'), ('epl league 2', 'epl2'), ('laliga', 'lg'), ('Serie A', 'sa'), ('Serie B', 'sb'), ('Bundesliga', 'bg')], max_length=100),
        ),
    ]
